[project]
name = "checkio"
version = "0.1.0"
description = "first step with poetry"
authors = [
    {name = "alexandre.wallez",email = "alexandre.wallez.etu@univ-lille.fr"}
]
readme = "README.md"
requires-python = ">=3.13"s
dependencies = [
]

[tool.poetry]
packages = [{include = "checkio", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
