name: GitHub Actions
run-name: ${{ github.actor }} compile pytest
on: 
  push :

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
       contents: write
       
    steps:

      - uses: actions/checkout@v4
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - run: poetry install 

      - run: |
          poetry run pytest tests/
          poetry run coverage run -m pytest
          poetry run coverage report -m
          
      - uses: tj-actions/coverage-badge-py@v2

      - run: |
          git add coverage.svg
          git commit -m "Update coverage badge [bot]" 
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
